//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GRID_Excel_POC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class dbTransferDeskService_DevEntities1 : DbContext
    {
        public dbTransferDeskService_DevEntities1()
            : base("name=dbTransferDeskService_DevEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<GetLinkInstitutesDataFromGrid_Result> GetLinkInstitutesDataFromGrid()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetLinkInstitutesDataFromGrid_Result>("GetLinkInstitutesDataFromGrid");
        }
    
        public virtual ObjectResult<pr_GetDomainList_Result> pr_GetDomainList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_GetDomainList_Result>("pr_GetDomainList");
        }
    }
}
